# Generated by Django 3.2.20 on 2023-09-17 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('org_number', models.CharField(blank=True, max_length=225, null=True)),
                ('address1', models.CharField(blank=True, max_length=225, null=True)),
                ('address2', models.CharField(blank=True, max_length=225, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=225, null=True)),
                ('place', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_refrence', models.CharField(blank=True, max_length=225, null=True)),
                ('sender_refrence', models.CharField(blank=True, max_length=225, null=True)),
                ('invoice_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit Note', 'Credit Note')], default='Invoice', max_length=20)),
                ('due_days', models.IntegerField(default=14)),
                ('is_send', models.BooleanField(default=False)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoice', to=settings.AUTH_USER_MODEL)),
                ('is_credit_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_invoice', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='team.team')),
            ],
        ),
    ]
