# Generated by Django 3.2.20 on 2023-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
